### ISSUE TITLE
ghmattimysql for Cops FiveM

### ISSUE THREAD

**Issue by asheppard1** [GHMatti/ghmattimysql#13]
Hi,

I get the following issue on when connecting to my local windows server. I execute ghmattimysql fine from the cfg file. I've editted the config.json file but not sure what to change for the SQL connection screen. I already use set mysql_connection_string "server=localhost;database=essentialmode;userid=root;" for mysql-async and dont want to install SQL again or another way. I currently use XAMPP. All details are correctly.

![image](https://user-images.githubusercontent.com/41967063/56437180-56c84680-62d6-11e9-8971-120ff18af85c.png)

Help!

**Comment by jadamconnor** [comment]
**Problem(s):** (skip to solution for solution)
Since you posted this 7 days ago, I assume you moved on by now, but your first problem is that the file structure of this release (1.1.0) is such that if you extract or clone directly into resources the `__resource.lua` (the resource manifest) is buried two directories deep (`srs/static/__resource.lua`). This will cause fivem to be unable to load the resource.

The second problem with 1.1.0 is that it's missing the file that exposes the necessary functions (ghmattimysql.js), so even if you knew to get rid of everything except the contents of /static you'd get an error telling you that there is `no such export execute in ghmattimysql`.

**Solution:**
Use [release 1.0.0](https://github.com/GHMatti/ghmattimysql/releases/download/1.0.0/ghmattimysql-1.0.0.zip). Just drop the ghmattimysql from that release into your resources folder and make sure you remember to add `start ghmattimysql` to your server config before any resources that rely on it.

**Comment by asheppard1** [comment]
thanks for the advice

**Comment by GHMatti** [comment]
People should always use the release version. The src stuff is only if someone wants to use it to do their own stuff.
